#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

# Battery Defaults
param set-default BAT_N_CELLS 6
param set-default BAT1_N_CELLS 6

# Log everything
param set-default SDLOG_PROFILE 5
param set-default SDLOG_MODE 2
param set-default COM_ARM_SDCARD 1

# update control defaults
param set-default MPC_Z_VEL_MAX_UP 1.5
param set-default MPC_Z_VEL_MAX_DN 1.5
param set-default MPC_POS_MODE 1
param set-default MPC_MAN_TILT_MAX 20
param set-default MPC_THR_HOVER 0.1

# selective disabling of various arming / disarming checks
param set-default FD_FAIL_R 0		# allow arming at any Roll angle
param set-default FD_FAIL_P 0		# allow arming at any Pitch angle
param set-default COM_ARM_CHK_ESCS 0	# ignore ESCS arming check
param set-default COM_ARM_CHK_ACC 0	# ignore Accelerometer arming checking
param set-default COM_ARM_CHK_BIAS 0	# ignore EKF2 sensor bias arming check
param set-default COM_DISARM_PRFLT -1.0	# don't automatically disarm if preflight checks fail
param set-default COM_DISARM_LAND -1.0	# don't automatically disarm when landed
#param set-default COM_ARM_CHK_PREF 0	# disable all pre-flight arm checks

# misc.
param set-default MC_AIRMODE 0 		# can consider using '1' for roll/pitch. Don't use '2' b/c yaw has issues.
param set-default EKF2_GND_EFF_DZ 4 	# this is default but we initially had it set to 0. Should we go back to 0?
#param set-default CAL_MAG0_ROT 6 	# YAW 270 for yhid pixhawk/holybro board
param set-default LND_FLIGHT_UNCRT 1 	# don't trust the landing detector for arm / disarm checks.

set MIXER quad_w
