#!/bin/sh
# SITL
# @name NHB_RevB
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

# Differences on review

# Simulation had 60 Hz for DGyro Cutoff
# param set-default IMU_DGYRO_CUTOFF 20.0000

# Already known! : Failsafe behavior and parameters were removed
# param set-default COM_DISARM_LAND, COM_RCL_ACT_T


## All acro parameters were different IE SIM is faster rates
# RC controller feel params
# param set-default MC_ACRO_EXPO 0.3000
# param set-default MC_ACRO_EXPO_Y 0.3000
# param set-default MC_ACRO_P_MAX 900.0000
# param set-default MC_ACRO_R_MAX 900.0000
# param set-default MC_ACRO_SUPEXPO 0.8400
# param set-default MC_ACRO_SUPEXPOY 0.8400
# param set-default MC_ACRO_Y_MAX 900.0000

. ${R}etc/init.d/rc.mc_defaults

# This parameter is a kludge is the code that defines behaviors specific to modal vehicles
# Be careful items and features defined under ut could easily be moved outside of its scope
param set-default MODALAI_CONFIG 1

## COPIED Params from 22200_nhb_revB_voxl2 on July 12, 2023

# Battery Parameters
# Note we do not actually use the capacity estimates for failsafes or user notifications
# Thus they may be populated here but could be incorrect
param set-default BAT1_CAPACITY 1300.0000
param set-default BAT1_N_CELLS 6
param set-default BAT1_R_INTERNAL 0.0060
param set-default BAT_N_CELLS 6
param set-default BAT_LOW_VOLT 21.8
param set-default BAT_LOW_V_TIME 10
param set-default BAT_LOW_THR 0.0
param set-default BAT_CRIT_THR 0.0
param set-default BAT_EMERGEN_THR 0.0
param set-default BAT1_V_EMPTY 3.5


# Control Allocator
param set-default CA_R_REV 0
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# PX4 Motor #1
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.19
param set-default CA_ROTOR0_KM 0.050

# PX4 Motor #2
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.17
param set-default CA_ROTOR1_KM 0.050

# PX4 Motor #3
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.19
param set-default CA_ROTOR2_KM -0.05

# PX4 Motor #4
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.17
param set-default CA_ROTOR3_KM -0.05

# arming / disarming params
param set-default COM_ARM_EKF_BIAS 0.0000
param set-default COM_ARM_EKF_HGT 0.0000
param set-default COM_ARM_EKF_VEL 0.000
param set-default COM_ARM_EKF_POS 0.000
param set-default COM_ARM_EKF_YAW 0.000

# COM_BAT_ACT_T 10.0 (old default) vs 5.0 new default
# https://github.com/PX4/PX4-Autopilot/commit/455b885f86754985fb07726b7975f0f028537204#diff-98b4e0f87126f3486c8dda8f693ee45c682a856f17958aed5a33d51e5fd27766L300
# Renamed COM_BAT_ACT_T  -> COM_FAIL_ACT_T
# I do not like this as it could?? affect other failsafe types other than battery?
# change in behavior?
#
# For now leave at new default
# param set-default COM_FAIL_ACT_T 10.0

# note these Probably doesnt matter
# COM_POS_FS_EPV 10

param set-default COM_ARM_BAD_INOV 1
param set-default COM_ARM_IMU_ACC 0.0
param set-default COM_ARM_IMU_GYR 0.0
param set-default COM_ARM_MAG_ANG -1
###### SIMULATION Parameters ######
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# RC controller mapping params
param set-default COM_FLTMODE1 1
param set-default COM_FLTMODE2 1
param set-default COM_FLTMODE3 1
param set-default COM_FLTMODE4 1
param set-default COM_FLTMODE5 1
param set-default COM_FLTMODE6 1

# Bootup Flight Mode is Altitude Hold
param set-default COM_FLTMODE_INIT 1

param set-default COM_DISARM_FORCE 1
param set-default COM_DISARM_PRFLT -1.0000
param set-default FD_FAIL_P 180
param set-default FD_FAIL_R 180

# EKF params

# Vision Position Estimator Params?
# Boson Related?
# Modal changed it to this
param set-default EKF2_EV_DELAY 5

# Optical flow params
# EKF2_OF_DELAY 20.0 ms (default) or 80.0 ms on Modal Params
# EKF2_OF_N_MIN 0.15 rad/s vs default of 0.5 rad/s

# Turn off Fake Position Fusion
param set-default EKF2_FP_ALIM 0.0

# EKF_AID mask (nomral == 0)  (2 == enable optical fusion)
param set-default EKF2_AID_MASK 0

# GPS do not fuse any gps readings into the EKF
param set-default EKF2_GPS_CTRL 0

# EKF2_IMU_CTRL disable accel and gyro bias estimation and enable gravity fusion
param set-default EKF2_IMU_CTRL 4
param set-default EKF2_GRAV_NOISE 1.0

# Default (old/new) 3.5m  vs. Modal had 0.75m
# param set-default EKF2_BARO_NOISE 0.75
param set-default EKF2_GND_EFF_DZ 0.0

param set-default EKF2_HGT_REF 0
param set-default EKF2_MAG_TYPE 5

# Single-instance EKF Params
# These changed ??? ot N/A
# While we should have plenty of power for many ekf lanes
# it does open up more code
param set-default SENS_MAG_MODE 1
param set-default SENS_IMU_MODE 1
param set-default EKF2_MULTI_MAG 0
param set-default EKF2_MULTI_IMU 0

param set-default EKF2_GPS_CHECK 0
param set-default EKF2_MAG_CHECK 0
# param set-default EKF2_MCOEF 0.3200

# EKF Range Finder Params
param set-default EKF2_RNG_CTRL 0
# EKF2_RNG_A_HMAX 5.0 (default) or modal 1.0
# EKF2_RNG_NOISE 0.1 (default) or 1.0

param set-default EKF2_IMU_POS_Y -0.0155
param set-default EKF2_IMU_POS_Z 0.0040

# GPS EKF Checks
param set-default EKF2_REQ_EPH 6.0000
param set-default EKF2_REQ_EPV 10.0000
param set-default EKF2_REQ_PDOP 3.5000
param set-default EKF2_REQ_SACC 1.0000

# Geofence
param set-default GF_ACTION 1

# GPS
# uneeded  I think??
# param set-default GPS_1_CONFIG 201
# GPS_UBX_DYNMODEL 6 or Modal 7 (default)
# We may want to change to
# param set-default GPS_UBX_DYNMODEL 6

# Hover Thrust Estimator Params
# We have problems with this section of code and need to work on all the HTE params
param set-default HTE_HT_NOISE 0.0005

# MPC_THR_HOVER should be between hover thrust estimator's min/max
# We need to test this minimum further... especially during ground effect to find the true minimum hover level.
# Note previously HTE_THR_MIN was effectively 0.0
param set-default HTE_THR_MIN 0.05
param set-default HTE_THR_MAX 0.6

# IMU noise filtering params
param set-default IMU_GYRO_RATEMAX 800
param set-default IMU_DGYRO_CUTOFF 20.0000
param set-default IMU_GYRO_CUTOFF 180.0000
param set-default IMU_GYRO_DNF_BW 20.0000
param set-default IMU_GYRO_DNF_EN 2

# IMU FFT Filtering
param set-default IMU_GYRO_FFT_EN 1
param set-default IMU_GYRO_FFT_LEN 1024
param set-default IMU_GYRO_FFT_MAX 192.0000
param set-default IMU_GYRO_FFT_MIN 32.0000

# Shows as N/A on vehicle but can be in the code on 1.14?
# This module might not be starting?
# param set-default IMU_GYRO_CAL_EN 1

# Doesn't exist
# param set-default COM_RCL_ACT_T 3.000

# Time-out for auto disarm after landing
# FIXME Only disarms if it detects landing
param set-default COM_DISARM_LAND 0.5
param set-default MPC_LAND_SPEED 3.0

# Land Detector
# Turns off ground effect compensation ??
#  * The height above ground below which ground effect creates barometric altitude errors.
#  * A negative value indicates no ground effect.
#  * The landing detector is dependent on the Z-axis velocity. The z-axis velocity must be below LNDMC_Z_VEL_MAX.
#  * MPC_LAND_CRWL must be set 1.2 times bigger than LNDMC_Z_VEL_MAX. If not, LNDMC_Z_VEL_MAX get lowered automatically.
param set-default LNDMC_Z_VEL_MAX 0.50
param set-default MPC_LAND_CRWL 1.0
param set-default LNDMC_ALT_GND -1.0000

# Commander RC Parameters
# param set-default COM_RC_IN_MODE 0   SET for simulation to allow use of the joystick from QGC, 2 = RC and Joystick with fallback
param set-default COM_RC_LOSS_T 0.3

# Navigation
# LAND the vehicle after the time given by COM_RC_LOSS_T in seconds
param set-default NAV_RCL_ACT 3

# Commander Offboard Control Params
param set-default COM_OF_LOSS_T 3.000

# MAVLINK Configs parameters come back to these. I'm not
# how these get used can't find like the others easily in the code
# IE MAV_x_CONFIG
# param set-default MAV_1_MODE 0


# Module: magnetometer_bias is not starting
# These are N/A on vehicle
# MBE_ENABLE & MBE_LEARN_GAIN

#Set the vehicle type to Quadrotor
param set-default MAV_TYPE 2

# Turn off Arm/Disarm using stick gestures
param set-default MAN_ARM_GESTURE 0

# FIXME COME BACK TO MC MPC
# in course params
# MC_AT_EN 1  auto tune is enabled !!!!
# also that param is not found in 1.14
# module not started

# RC controller feel params
param set-default MC_ACRO_EXPO 0.69
param set-default MC_ACRO_EXPO_Y 0.69
param set-default MC_ACRO_P_MAX 720.0
param set-default MC_ACRO_R_MAX 720.0
param set-default MC_ACRO_SUPEXPO 0.70
param set-default MC_ACRO_SUPEXPOY 0.70
param set-default MC_ACRO_Y_MAX 540.0

### Actual Vehicle PID controller tuning params
# On the orignal simulation these were all turned off
# We should actually tune the vehicle in SITL and put the parameters here when done
###
# param set-default MC_PITCH_P 7.0
# param set-default MC_PITCH_CUTOFF 20.161
# param set-default MC_PITCHRATE_D 0.0016
# param set-default MC_PITCHRATE_I 0.771
param set-default MC_PITCHRATE_MAX 1600
# param set-default MC_PITCHRATE_P 0.110
# param set-default MC_ROLL_P 7.0
# param set-default MC_ROLL_CUTOFF 17.518
# param set-default MC_ROLLRATE_D 0.0014
# param set-default MC_ROLLRATE_I 0.705
param set-default MC_ROLLRATE_MAX 1600
# param set-default MC_ROLLRATE_P 0.101
# param set-default MC_YAW_P 1.5
# param set-default MC_YAW_CUTOFF 20.010
# param set-default MC_YAWRATE_I 6.30
param set-default MC_YAWRATE_MAX 1300.0000
# param set-default MC_YAWRATE_P 0.17

# Multi-Copter Position Control
# Flight Performance restriction params
param set-default MPC_MANTHR_MIN 0.0400
param set-default MPC_MAN_TILT_MAX 20.0000
param set-default MPC_TILTMAX_AIR 20.0000
param set-default MPC_MAN_Y_MAX 200.0

param set-default MPC_THR_MAX 0.8000
param set-default MPC_THR_MIN 0.0400
param set-default MPC_THR_HOVER 0.2000

param set-default MPC_JERK_MAX 15.0000

## VEHICLE Settings current not used in SIM before
# XY Settings
# param set-default MPC_XY_P 0.80
# param set-default MPC_XY_VEL_D_ACC 0.0
# param set-default MPC_XY_VEL_I_ACC 0.4000
# param set-default MPC_XY_VEL_P_ACC 1.2000
# OLD SIM PARAMS
param set-default MPC_XY_VEL_I_ACC 0.1000
param set-default MPC_XY_VEL_P_ACC 3.0000


# Z Settings
param set-default MPC_Z_P 0.3
param set-default MPC_Z_VEL_D_ACC 0.0
param set-default MPC_Z_VEL_I_ACC 4.8
param set-default MPC_Z_VEL_MAX_DN 1.5000
param set-default MPC_Z_VEL_MAX_UP 1.5000
param set-default MPC_Z_VEL_P_ACC 5.7000
param set-default MPC_Z_V_AUTO_UP 1.3000
param set-default MPC_Z_V_AUTO_DN 1.0

# MPC_POS_MODE -> Hold position with Velocity Input
param set-default MPC_POS_MODE 1

# On Screen Display (OSD) Params
param set-default OSD_CH_HEIGHT -2
param set-default OSD_SYMBOLS 786945
param set-default OSD_DWELL_TIME 750
param set-default OSD_LOG_LEVEL 4
param set-default OSD_SCROLL_RATE 100
param set-default OSD_BATT_LOW_V 21.8

# Parameter Selector Module
param set-default SELECTOR_ENABLED 1
param set-default PSET_MODE 3
param set-default PSET_CHANNEL 6

# FIXME Don't  know about these
# All are N/A on vehicle
# PWM_AUX_OUT 1234
# PWM_MAIN_MAX 1950
# PWM_MAIN_MIN 1075
# PWM_MAIN_OUT 1234
# PWM_MAIN_RATE 0

# Logging

# FIXME SDLOG_MODE is N/A need to confirm current log file behavior
# SDLOG_PROFILE i think we should customize this given we have a VOXL2 logging more and & makes sense for development
#
param set-default SDLOG_MODE 2
param set-default SDLOG_PROFILE 3

# Optical Flow Sensors
# param set-default SENS_FLOW_MINHGT 0.70
# param set-default SENS_FLOW_MAXR 2.5
# param set-default SENS_FLOW_ROT 2

# Magnetometer
param set-default SENS_MAG_AUTOCAL 0

# Multi-GPS blending control set to always use the first instance
param set-default SENS_GPS_MASK 0

# Temperature Calibration Parameters do not exist
# we may want these later
# module may not be starting
# SYS_CAL_ACCEL
# SYS_CAL_GYRO
# etc

# Sensor Drivers
# Enable GPS
# Disable magnetometer for now
param set-default SYS_HAS_GPS 1
param set-default SYS_HAS_MAG 0

# System Checks and Config
# param set-default SYS_DM_BACKEND 1

# Enables Stack checking
# param set-default SYS_STCK_EN 1

param set-default THR_MDL_FAC 0.8069

###### SIMULATION Specific Parameters ######
# param set-default SIM_GZ_EN 1

# These parameters map to the motors
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default SYS_AUTOCONFIG 1 	# reset params each boot
param set-default COM_RC_IN_MODE 2 	# SET for simulation to allow use of the joystick from QGC, 2 = RC and Joystick with fallback
