module_name: ManualAltitudeCommandVel
parameters:
- group: Flight Task Manual Altitude Velocity
  definitions:
    FLGT_ACC_LIM_UP:
      description:
        short: Vertical velocity setpoint slew limit climbing
        long: |-
          Maximum rate of change applied to the commanded vertical velocity
          setpoint while increasing climb rate. This prevents abrupt throttle
          stick movements from producing a step in vertical velocity setpoint.

          Set to 0 to disable the slew limit.
      type: float
      default: 0.0
      unit: m/s^2
      min: 0.0
      max: 100.0
      increment: 0.01
      decimal: 3
    FLGT_ACC_LIM_DN:
      description:
        short: Vertical velocity setpoint slew limit descending
        long: |-
          Maximum rate of change applied to the commanded vertical velocity
          setpoint while increasing descent rate. This prevents slamming the
          throttle stick down from instantly cutting power to the motors.

          Set to 0 to disable the slew limit.
      type: float
      default: 0.0
      unit: m/s^2
      min: 0.0
      max: 100.0
      increment: 0.01
      decimal: 3
